mz07:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  mz07_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6

    gains: # Required because we're controlling an effort interface
      J1: {p: 100.0, i: 10.0, d: 0.0, i_clamp: 100.0}
      J2: {p: 1000.0, i: 500.0, d: 0.0, i_clamp: 500.0}
      J3: {p: 100.0, i: 10.0, d: 0.0, i_clamp: 100.0}
      J4: {p: 100.0, i: 10.0, d: 0.0, i_clamp: 100.0}
      J5: {p: 10.0, i: 1.0, d: 0.0, i_clamp: 100.0}
      J6: {p: 10.0, i: 1.0, d: 0.0, i_clamp: 100.0}
